site_name: Solderen
site_url: "https://kenzanin.github.io"
edit_uri: "tree/main/docs/"
repo_url: "https://github.com/kenzanin/kenzanin.github.io"

extra:
  disqus: kenzanin-github-io
  social:
    - icon: "fontawesome/brands/telegram"
      link: https://telegram.me/kenzanin
      name: kenzanin
    - icon: "fontawesome/brands/whatsapp"
      link: https://wa.link/q6rses
      name: suka isnaini
    - icon: "fontawesome/solid/at"
      link: mailto:kenzanin@gmail.com
      name: kenzanin

plugins:
  - search
  - macros:
      include_yaml:
        #- "docs/lang/clang/variables.yml"
        #- "docs/mcs51/variables.yml"
      include_dir: docs
  - git-revision-date-localized
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
  - awesome-pages

theme:
  name: material
  font:
    text: JetBrains Mono
    code: consolas
  features:
#    - tabs
    #- navigation.sections
  palette:
    scheme: slate

markdown_extensions:
  - pymdownx.keys
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx.inline
      linenums: true
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
      base_path: docs
  - admonition
  - abbr
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - markdown_include.include:
      base_path: docs
  - attr_list
  - footnotes
  - meta
  - pymdownx.magiclink
  - pymdownx.pathconverter
  - pymdownx.inlinehilite

copyright: Copyright &copy; 2021 [Suka Isnaini]

google_analytics:
  - G-D8BVSGRXC8
  - auto
